import type { Metadata } from "next";
import './styles/global.module.scss';
import localFont from 'next/font/local';
import { ReactNode } from "react";

const helvetica = localFont({
  src: [
    {
      path: './styles/fonts/HelveticaNeueCyr-Light.ttf',
      weight: '300'
    },
    {
      path: './styles/fonts/HelveticaNeueCyr-Roman.ttf',
      weight: '400'
    },
    {
      path: './styles/fonts/HelveticaNeueCyr-Medium.ttf',
      weight: '500'
    },
    {
      path: './styles/fonts/HelveticaNeueCyr-Bold.ttf',
      weight: '700'
    },
  ]
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.className}>{children}</body>
    </html>
  )
}
